# Configuration file for NTU60 dataset and VPN as the model 
---

# Dataset Parameters
num_classes : 6
protocol : 'cs'
train_ds_name : 'train'
test_ds_name : 'validation'
num_nodes : 14  # This project we only work with 14 joints
stack_size : 16
n_neuron : 64
n_dropout : 0.3
timesteps : 16

# GCN parameters
num_features : 2
sym_norm : True

# File Locations
paths:
  skeleton :  '../skeleton/vpn_2d_npy/'
  cnn: '../video/'
  split_path: '../splits/'


# Training/Testing Parameters
action_wt : 0.9
embed_wt : 0.1
lr : 0.01
momentum : 0.01
batch_size : 4
weights_loc: './best'
multi_proc: False

